CREATE DATABASE LZYDBTEST;
USE LZYDBTEST;  

CREATE TABLE ACCOUNTS(
	ID INT NOT NULL AUTO_INCREMENT,
	NICK VARCHAR(30) NOT NULL UNIQUE,
	PASSWORD BINARY(64) NOT NULL,
	EMAIL VARCHAR(320) NOT NULL UNIQUE,
	STRIKES TINYINT NOT NULL,
	USER_TYPE CHAR(1) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE POSTS(
	ID INT NOT NULL AUTO_INCREMENT,
	CREATE_DATE DATE NOT NULL,
	UPDATE_DATE DATE NOT NULL,
	AUTHOR INT NOT NULL,
	IS_REVIEWED BIT NOT NULL,
	REVIEWED_BY INT,
	IS_DELETED BIT,
	TITLE VARCHAR(100),
	URL VARCHAR(2048),
	POST_TYPE CHAR (1),
	PRIMARY KEY (ID),
    FOREIGN KEY (REVIEWED_BY) REFERENCES ACCOUNTS(ID),
	FOREIGN KEY (AUTHOR) REFERENCES ACCOUNTS(ID)
);

CREATE TABLE TAGS(
	ID INT NOT NULL AUTO_INCREMENT,
	TAG VARCHAR(45) UNIQUE NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE POSTS_TAGS(
	ID_POST INT NOT NULL,
	ID_TAG INT NOT NULL,
	FOREIGN KEY (ID_POST) REFERENCES POSTS(ID),
	FOREIGN KEY (ID_TAG) REFERENCES TAGS(ID)
);

CREATE TABLE BLOG_ENTRIES(
	ID_POST INT NOT NULL,
	TEXT_CONTENT TEXT NOT NULL,
	PRIMARY KEY(ID_POST),
	FOREIGN KEY (ID_POST) REFERENCES POSTS(ID)
);

CREATE TABLE LIKES(
	ID_POST INT NOT NULL,
	ID_USER INT NOT NULL,
	LIKED BIT NOT NULL,
	FOREIGN KEY (ID_POST) REFERENCES POSTS(ID),
	FOREIGN KEY (ID_USER) REFERENCES ACCOUNTS(ID)
);
